### ISSUE TITLE
Installer does nothing

### ISSUE THREAD

**Issue by jmuniz** [jfaustin/Tweet-gater#2]
Is there anything I am missing other than downloading the Zend framework and installing in the /inc/Zend folder?  After I install the framework all I get is a blank page when going to /install.

**Comment by jfaustin** [comment]
What version of PHP are you running?  ZF required php 5.2+.  That could be an issue.  Also do you have error_reporting turned on in your php.ini file?  If not, you can set <?php error_reporting(E_ALL); ?> on the install page and that may point you in the right direction.  Let me know if that doesn't work...

**Comment by jmuniz** [comment]
Thanks for the fast reply.  We are running PHP 5.2.8.  Even with the updated line you provided for the install/index.php I still receive just a blank page, it only contains <head> and <style> tags, no body to the document.

**Comment by jfaustin** [comment]
What version of ZF did you get?  The app requires 1.10.6 right now.  Also, did you download the 1.4 release or did you just export the code directly from git?

**Comment by jfaustin** [comment]
Also if you could tell me what OS and webserver you are running this on, that may help too...

**Comment by jmuniz** [comment]
Actually, that did it.  I was unaware there were two different downloads available.  The 1.4 release is now working.  Thanks for the fast replies!

**Comment by jfaustin** [comment]
Awesome.  Glad its working.  I'll look into why the straight-up export isn't work.  It should be...
