### ISSUE TITLE
Step 6: Authenticate with Twitter doesn't proceed

### ISSUE THREAD

**Issue by jmuniz** [jfaustin/Tweet-gater#3]
During the install I have gotten to step 6, however when clicking the link I am directed to the install/twitter_oauth.php and the page displays blank, no errors or any source code.

I have successfully created a new application with the Twitter account and received the consumer key and secrets and they show up properly in the config file.

**Comment by jfaustin** [comment]
What version of PHP are you running?  Zend Framework requires PHP 5.2+ so if you have something less it may not work with ZF's twitter oauth implementation.

**Comment by jmuniz** [comment]
Yes, I am running PHP 5.2.8 with Apache 2.2.9

**Comment by jfaustin** [comment]
Do you have error_reporting turned on in the file in question?  That may help track it down...

**Comment by jmuniz** [comment]
Yes, I have added the line error_reporting(E_ALL); to the twitter_oauth.php file and I still receive a blank page.

**Comment by jmuniz** [comment]
I switched error reporting around to a different setting, I received the following error:
Fatal error: Call to undefined function iconv_get_encoding() in /inc/Zend/Validate/Hostname.php on line 513

**Comment by jfaustin** [comment]
It looks like you don't have the iconv extension enabled on your PHP install.  Check out the info page here:  http://php.net/manual/en/book.iconv.php

Zend\Validate\Hostname uses that in the oauth packages to validate the URLs, so you are going to need that extension.  It's usually enabled by default, but perhaps your sysadmin disabled it for some reason.  You can tell for sure if you run phpinfo().

**Comment by jmuniz** [comment]
You are correct. I found out iconv was disabled during compile.  I have to wait for the admin to install, but that should be the fix.  Thanks.
