### ISSUE TITLE
Error on Authenticate

### ISSUE THREAD

**Issue by jmuniz** [jfaustin/Tweet-gater#4]
I receive the following error when clicking the Authenticate with Twitter link.  Any ideas to resolve would be appreciated.

Fatal error: Uncaught exception 'Zend_Session_Exception' with message 'Session must be started before any output has been sent to the browser; output started in /apache2/htdocs/twitter/install/twitter_oauth.php/2' in /apache2/htdocs/twitter/inc/Zend/Session.php:454 Stack trace: #0 /apache2/htdocs/twitter/inc/Zend/Session/Namespace.php(143): Zend_Session::start(true) #1 /apache2/htdocs/twitter/install/twitter_oauth.php(21): Zend_Session_Namespace->__construct('twitterAppAuthe...') #2 {main} thrown in /apache2/htdocs/twitter/inc/Zend/Session.php on line 454

**Comment by jmuniz** [comment]
Sorry.  I did some digging, apparently there is an errant space in the twitter_oauth.php at the beginning of the file which caused the error.  I deleted the extra space and it authenticated!

**Comment by jfaustin** [comment]
Was that in the source or just in your copy?  Doesn't look like there is a space in the current commit that I can find.

**Comment by jmuniz** [comment]
Looks like it was my copy.  I checked my original source copy and it too did not have the space.  Must have been accidentally added when I added debug code to the setup files.  Thanks for everything, we hope to implement it fully soon!
